### ISSUE TITLE
./types.h:86: error: field ‘time’ has incomplete type (using win32 flags)

### ISSUE THREAD

**Issue by silv3rr** [vgropp/bwm-ng#13]
To fix add ```#include <sys/time.h>```
This does not anything else and solves the issue for Windows... it seems :)
Did test compiling on Linux.

```diff
index 4321a2f..44cd685 100644
--- a/src/types.h
+++ b/src/types.h
@@ -23,6 +23,7 @@
 
 #ifndef __TYPES_H
 #define __TYPES_H
+#include <sys/time.h>
 #include "../config.h"
```

**Comment by vgropp** [comment]
should be fixed now in current master, thanks for reporting
