### ISSUE TITLE
'-u' option is not effective when csv output

### ISSUE THREAD

**Issue by CircleMan** [vgropp/bwm-ng#2]
for example, set '-u bits' and '-o csv' in same time, no change csv output format. (still print bytes_out/s;bytes_in/s;..)

**Comment by vgropp** [comment]
needs to rethink maybe, cause -o csv already include bytes, errors and packets, only bits is missing, so -u errors -o csv might be strange

**Comment by vgropp** [comment]
closed with #28 , bits are in csv output as well, might be BREAKING some csv outputs
