### ISSUE TITLE
Request - add column in display for corresponding IP address of interface

### ISSUE THREAD

**Issue by sjackson-adaptiv** [vgropp/bwm-ng#30]
Would it be possible to have the output include a column that displays of the corresponding IP address for a given interface? This would be really handy for systems with many interfaces.

For example, something like the following:
```
bwm-ng v0.6.X (probing every 0.500s), press 'h' for help
  input: /proc/net/dev type: rate
  |             ip        iface                  Rx                 Tx                    Total
  =============================================================================================
     192.168.1.254       ens20:           4.28 kb/s            0.00 kb/s              4.28 kb/s
     192.168.2.254       ens23:      390620.64 kb/s       375944.06 kb/s         766564.67 kb/s
     192.168.3.254        ens1:      374566.66 kb/s       390539.07 kb/s         765105.73 kb/s
     192.168.4.254       ens22:        2183.31 kb/s       184439.30 kb/s         186622.61 kb/s
     192.168.5.254       ens19:      370634.37 kb/s         4291.27 kb/s         374925.60 kb/s
     192.168.6.254       ens21:        2188.39 kb/s        184456.69 kb/s        186645.09 kb/s
     127.0.0.1              lo:           0.00 kb/s             0.00 kb/s             0.00 kb/s
     192.168.8.254       ens18:           0.96 kb/s             9.61 kb/s            10.57 kb/s
  ---------------------------------------------------------------------------------------------
                         total:      1140198.53 kb/s       1139680.00 kb/s       2279878.66 kb/s
```

**Comment by vgropp** [comment]
first thoughts:

- what about changes
- ipv4 vs ipv6 layout
- what about multiple addresses
- physical vs software/logical view

**Comment by g0tar** [comment]
- changes should be (not) supported the same way, as interface renames are (or not),
- IPv6 should be separate column,
- multiple addresses could be either folded to the first one (or the first "global" one in case on mixed global and local scopes) or unfolded to occupy multiple lines.

I on the other hand would like to see not the IP addresses (especially IPv6, they are mostly useless for manual handling), but their labels. I got all the addresses labeled by their function and they are human readable (interface names could be as well, but this could impede doing actual management), which is a must-have for many-interface scenarios.

**Comment by sjackson-adaptiv** [comment]
Sounds like it's not worth it then.
