### ISSUE TITLE
"-D 1" daemonize not working

### ISSUE THREAD

**Issue by bruno-anjos** [vgropp/bwm-ng#33]
Hi, so I was trying to use bwm-ng by launching it in the background and keeping track of the bandwidth usage. I tried in an alpine container, but for some reason it still grabs my shell and doesn't really fork into a background process. I thought this could be a alpine related problem, so I tried in a Ubuntu 19 (non container) and it behaved the same. So then I thought it could be an old version in the ubuntu repositories so I downloaded from git and built it myself. Same behaviour. No fork at all and holds my shell, by this I mean it produces measurements, but not in the background.

This is the command I ran:
`bwm-ng -t 1000 -I eth0 -o csv -c 10 -u bytes -T rate -F bandwidth_measures.csv -D 1`

Thank you.

**Comment by vgropp** [comment]
yes, dont know when this broke, there a autoconf test missing for fork, so support is not compiled in in latest versions

**Comment by vgropp** [comment]
should be fixed now in latest master, though you'll have to compile it yourself until its fixed in every distribution

**Comment by bruno-anjos** [comment]
That should be ok, I can compile it by hand. Thank you so much for the quick response and for the work you put in this.

**Comment by bruno-anjos** [comment]
On another note you might want to fix the readme that still refers the ./configure for the ./autogen.sh, if I'm not mistaken. Do you want me to submit a new issue with that?
