### ISSUE TITLE
Support console resize better

### ISSUE THREAD

**Issue by za3k** [vgropp/bwm-ng#35]
I use a tiling window manager. If I add a window, the bwm-ng resizes, and all numbers go to -nan/nan/-inf/inf. Depending on the mode, the output may self-correct. For example, 'rate' fixes this on the next update, while 'avg' leaves nan/inf forever.

Edit: In case this is needed for repro, I'm typically using bwm-ng inside tmux over ssh

**Comment by za3k** [comment]
Duplicate of #16 and already fixed (just not in debian stable yet)

**Comment by vgropp** [comment]
actually debian stable version 11, codename bullseye now includes bwm-ng 0.6.3 which includes the fix from #16, do you still encounter the issue?

**Comment by za3k** [comment]
Yes, I do still encounter the issue in 0.6.3 (it's quite hard to figure out what version a git commit was released in, thanks!)

**Comment by vgropp** [comment]
Any news on this? Are you able to reproduce it?
